name: Hello world

on: [push]

jobs:
  fetch_and_commit:
    runs-on: ubuntu-latest

    # outputs:
    #   changes: ${{ steps.check_changes.outputs.changes }}

    steps:
      - name: Check for changes
        id: check_changes
        run: echo "changes=$(($RANDOM % 2))" >> $GITHUB_OUTPUT

      - name: Commit and push if changes
        run: |
          if ${{ steps.check_changes.outputs.changes }}; then
          echo changed!;
          else
          echo not change;
          fi
